QT          += core gui widgets serialport printsupport
TARGET      = Ultrasonic
TEMPLATE    = app
CONFIG      += c++11
SOURCES     += main.cpp window.cpp qcustomplot.cpp ultrasonic.cpp about.cpp
HEADERS     += window.h qcustomplot.h ultrasonic.h about.h
FORMS       += window.ui about.ui
RESOURCES   += resources.qrc
RC_FILE     = resources.rc